### ISSUE TITLE
wsl+ windows terminal下proxy tab 显示不正常

### ISSUE THREAD

**Issue by hongy19** [George-Miao/clashctl#27]
在wsl + windows terminal下proxy tab显示不正常

<img width="415" alt="Screenshot 2023-04-05 210638" src="https://user-images.githubusercontent.com/7909177/230089743-0f904375-66d6-4599-9ee0-305713d9d197.png">

**Comment by George-Miao** [comment]
抱歉我本人不用 windows，也没有在 windows 上测试过。如果你知道解决方法请发一个 PR。
