### ISSUE TITLE
Support Premium Core

### ISSUE THREAD

**Issue by rainbowflesh** [George-Miao/clashctl#30]
Gotta bug when using premium core feature:
```txt
thread '<unnamed>' panicked at clashctl/src/ui/components/proxy/tree.rs:205:26:
Group member should be in all proxies
```

**Comment by George-Miao** [comment]
Sorry but there's no plan to support close-source core. However I'm happy to accept any PR that add such functionality.

**Comment by rainbowflesh** [comment]
> Sorry but there's no plan to support close-source core. However I'm happy to accept any PR that add such functionality.

I've been reading this repo's code and adding premium core support, I'll PR when it's ready ;)

**Comment by George-Miao** [comment]
> I'll PR when it's ready ;)

That will be helpful! Thanks in advance.
